KINVEST_METADATA_NETWORK=kinvest-metadata-egress
KINVEST_METADATA_SUBNET=172.31.252.0/29
KINVEST_METADATA_GATEWAY=172.31.252.1
KINVEST_CONTAINER_NAME=kinvest
KINVEST_CONTAINER_IP=172.31.252.2
KINVEST_BRIDGE_INTERFACE=br-kinvest-meta
KINVEST_METADATA_IP=169.254.0.23
